#NumPy - "Numerical Python" Basic

In [ ]:
import numpy as np

In [ ]:
make_an_array = np.array([1,2,3,5,7])

print(make_an_array)

string_array =  np.array(['R', 'K', 'J'])
print("array as string :", string_array)


dimension_1d_array = np.array(69)
print("1d array:", dimension_1d_array)
print("dimensions:",dimension_1d_array.ndim)


dimension_1d_array_multiple_value = np.array([1,3,5,7,9])
print(dimension_1d_array_multiple_value)
print("dimensions:",dimension_1d_array_multiple_value.ndim)




dimension_2d_array = np.array([[1,2,4,6,8],[1,3,5,7,9]])
print("2d array:" , dimension_2d_array)
print("dimensions:", dimension_2d_array.ndim)




dimension_3d_array = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print("3d array:" , dimension_3d_array)
print("dimensions:", dimension_3d_array.ndim)



higher_dimension = np.array([1, 2, 3, 4], ndmin=7)

print("any dimensions:", higher_dimension)
print('dimensions:', higher_dimension.ndim)






[1 2 3 5 7]
array as string : ['R' 'K' 'J']
1d array: 69
dimensions: 0
[1 3 5 7 9]
dimensions: 1
2d array: [[1 2 4 6 8]
 [1 3 5 7 9]]
dimensions: 2
3d array: [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
dimensions: 3
any dimensions: [[[[[[[1 2 3 4]]]]]]]
dimensions: 7


Slicing arrays :
[start:end],
[start:end:step]

In [ ]:
array_method_apply = np.array([1,2,3,4,5,6,7])

print("[1:5] :",array_method_apply[1:5])

print("[:5] :",array_method_apply[:5])

print("[5:] :",array_method_apply[5:])

print("[::3] :",array_method_apply[::3])

print("[-3:-1] :",array_method_apply[-3:-1])

[1:5] : [2 3 4 5]
[:5] : [1 2 3 4 5]
[5:] : [6 7]
[::3] : [1 4 7]
[-3:-1] : [5 6]


In [ ]:

array = np.array([1, 2, 3, 4, 5,6,7,8,9])

#copy() - it will change but didn't update

copy_array= array.copy()
array[0] = 69

print(array)
print(copy_array)

#view() - it will change and update the value

viewed_array = array.view()
viewed_array[0] = 39

print(array)
print(viewed_array)

# shape
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

print('shape of array :', arr.shape)

# reshape

shaped_array = array.reshape(3, 3)

print("row(3) * column(3):", shaped_array)

# array 1d to 3d reshape

arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

array_1d_to_3d = arr_1d.reshape(2, 3, 2)

print("array(2)- row(3)- column(3):", array_1d_to_3d)

# base

print("base of array:", array_1d_to_3d.base)


[69  2  3  4  5  6  7  8  9]
[1 2 3 4 5 6 7 8 9]
[39  2  3  4  5  6  7  8  9]
[39  2  3  4  5  6  7  8  9]
(2, 4)
shape of array : (2, 4)
row(3) * column(3): [[39  2  3]
 [ 4  5  6]
 [ 7  8  9]]
array(2)- row(3)- column(3): [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
base of array: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print("x:", x)
  for y in x:
    print(" \n y:",y)
    for z in y:
      print("z:", z)


for  x in np.nditer(arr):
  print( x)

for idx, x in np.ndenumerate(arr):
   print(idx, x)



x: [[1 2 3]
 [4 5 6]]
 
 y: [1 2 3]
z: 1
z: 2
z: 3
 
 y: [4 5 6]
z: 4
z: 5
z: 6
x: [[ 7  8  9]
 [10 11 12]]
 
 y: [7 8 9]
z: 7
z: 8
z: 9
 
 y: [10 11 12]
z: 10
z: 11
z: 12
1
2
3
4
5
6
7
8
9
10
11
12
(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 10
(1, 1, 1) 11
(1, 1, 2) 12


In [ ]:
# array Filter

arr = np.array([1, 2, 3, 4, 5, 6, 7])


filter_arr = []

for element in arr:

  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)






[False, True, False, True, False, True, False]
[2 4 6]


In [ ]:
# array sort

array = np.array([["md","k","j","r"],[3,7,5,9]])

arr_sort = np.sort(array)
print(arr_sort)


[['j' 'k' 'md' 'r']
 ['3' '5' '7' '9']]


In [ ]:

# array search

arr = np.array([1,2,3,4,5,6,7,8,9])

search_array = np.where( arr%2 == 0)

print(search_array)


x = np.searchsorted(arr, 9)

print(x)

newarr = np.array_split(arr, 3)

print(newarr)

(array([1, 3, 5, 7]),)
8
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [ ]:
# array join




# Numpy "distributions"

# Numpy "Universal-Function"

In [ ]:
arr_1 = np.array([10,20,30,40,50])
arr_2 = np.array([100,200,300,400,500])
arr_3 = np.array([1,3,5,7,9])

# addition
added_arr = np.add(arr_1, arr_2)
print("The addition of arrays:" ,added_arr)

# subtraction
substracted_arr = np.subtract(arr_1,arr_2)
print("The subtraction of arrays:", substracted_arr)

# multiplication

multiplication_arr = np.multiply(arr_1, arr_2)
print("The multiplication of arrays:", multiplication_arr)

# division
division_arr = np.divide(arr_2,arr_1)
print("The division of arrays:", division_arr)


# power
power_arr = np.power(arr_1, arr_3)
print("The power of arrays:", power_arr)

# mod
mod_arr = np.mod(arr_1,arr_3)
print("The mod of arrays:", mod_arr)

#remainder
remainder_arr = np.remainder(arr_1,arr_3)
print("the remainder of arrays:", remainder_arr)

# Quotient and Mod

quotient_mod = np.divmod(arr_1,arr_3)
print(quotient_mod)


The addition of arrays: [110 220 330 440 550]
The subtraction of arrays: [ -90 -180 -270 -360 -450]
The multiplication of arrays: [ 1000  4000  9000 16000 25000]
The division of arrays: [10. 10. 10. 10. 10.]
The power of arrays: [              10             8000         24300000     163840000000
 1953125000000000]
The mod of arrays: [0 2 0 5 5]
the remainder of arrays: [0 2 0 5 5]
(array([10,  6,  6,  5,  5]), array([0, 2, 0, 5, 5]))


In [ ]:

# array using arange

arr = np.arange(1,10)

# Log at Base 2
arr_base_2 = np.log2(arr)
print("log2:",arr_base_2)



# Log at Base 10
arr_base_10 =  np.log10(arr)
print("log10:", arr_base_10)


# normal log
normal_log = np.log(arr)
print(normal_log)




log2: [0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]
log10: [0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


In [ ]:
arr1 = np.array([10,20,30,40,50])
arr2 = np.array([1,3,5,7,9])

# summation

sum_arr =  np.sum([arr1, arr2])

print("the sum of both arrays:", sum_arr)


# difference

diff_arr = np.diff([arr1, arr2])

print("the sum difference of both arrays", diff_arr)




# products

prod_arr = np.prod([arr2, arr1])
print("the sum product of both arrays:", prod_arr)


#lcm

lcm = np.lcm.reduce(arr2)
print("lcm:", lcm)


#lcm

gcd = np.gcd.reduce(arr1)
print("gcd:", gcd)


the sum of both arrays: 175
the sum difference of both arrays [[10 10 10 10]
 [ 2  2  2  2]]
the sum product of both arrays: 11340000000
lcm: 315
gcd: 10


In [ ]:
arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])

x = np.rad2deg(arr)


arr = np.array([1, -1, 0.1])

x = np.arcsin(arr)
